# Generated by Django 2.0.1 on 2018-01-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0002_auto_20180114_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpaneldispla',
            old_name='producent_panelu',
            new_name='numer_palety',
        ),
        migrations.RenameField(
            model_name='flatpaneldispla',
            old_name='rozmiar_panelu',
            new_name='producent_ekranu',
        ),
        migrations.RenameField(
            model_name='flatpaneldispla',
            old_name='umer_palety',
            new_name='rozmiar_ekranu',
        ),
    ]
