# Generated by Django 2.0.1 on 2018-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0003_auto_20180114_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekran', models.CharField(choices=[('14"', '14"'), ('17"', '17"'), ('19"', '19"'), ('21"', '21"')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FlatPanelDispla',
        ),
    ]
