# Generated by Django 2.0.1 on 2018-01-14 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0004_auto_20180114_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='ekran',
        ),
        migrations.AddField(
            model_name='panel',
            name='data_testu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 21, 28, 5, 254814)),
        ),
        migrations.AddField(
            model_name='panel',
            name='numer_kartonu',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='panel',
            name='numer_palety',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='panel',
            name='osoba_testujaca',
            field=models.CharField(default='Jan Kowalski', max_length=200),
        ),
        migrations.AddField(
            model_name='panel',
            name='producent_ekranu',
            field=models.CharField(choices=[('wybierz', 'wybierz'), ('SAMSUNG', 'SAMSUNG'), ('LG', 'LG'), ('ASUS', 'ASUS'), ('PHILIPS', 'PHILIPS')], default='wybierz', max_length=100),
        ),
        migrations.AddField(
            model_name='panel',
            name='rozmiar_ekranu',
            field=models.CharField(choices=[('wybierz', 'wybierz'), ('14', '14"'), ('17', '17"'), ('19', '19"'), ('21', '21"')], default='wybierz', max_length=100),
        ),
    ]
