# Generated by Django 2.0.1 on 2018-01-14 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agat', '0005_auto_20180114_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='data_testu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 21, 29, 14, 265872)),
        ),
        migrations.AlterField(
            model_name='panel',
            name='numer_kartonu',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='numer_palety',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='producent_ekranu',
            field=models.CharField(blank=True, choices=[('wybierz', 'wybierz'), ('SAMSUNG', 'SAMSUNG'), ('LG', 'LG'), ('ASUS', 'ASUS'), ('PHILIPS', 'PHILIPS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='panel',
            name='rozmiar_ekranu',
            field=models.CharField(blank=True, choices=[('wybierz', 'wybierz'), ('14', '14"'), ('17', '17"'), ('19', '19"'), ('21', '21"')], max_length=100),
        ),
    ]
